"""Add counts to repository

Revision ID: ba2b9033a6d7
Revises: 
Create Date: 2026-06-22 17:14:10.315560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2b9033a6d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('contributor_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repositories', sa.Column('pr_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repositories', sa.Column('discussion_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('repositories', sa.Column('contribution_opportunities', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'contribution_opportunities')
    op.drop_column('repositories', 'discussion_count')
    op.drop_column('repositories', 'pr_count')
    op.drop_column('repositories', 'contributor_count')
    # ### end Alembic commands ###
